# Generated by Django 4.0.3 on 2022-08-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.URLField(default=None, unique=True),
        ),
    ]
