# Generated by Django 4.0.3 on 2022-08-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_project_repo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.URLField(),
        ),
    ]
